#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3
bspc config top_padding 40
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 0
bspc config window_gap 12
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
picom --config $HOME/.config/picom/picom.conf &
xfsettingsd &
polybar &
xfce4-panel &
Thunar --daemon &
nitrogen --restore &
sleep 5
xborder --border-rgba "#F5C2E7E6" --border-width 3 --border-mode center --border-radius 12 --disable-version-warning &